language: python
python:
    - "3.10.1"
install:
    - pip install -r requirements.txt
script:
    - flake-8
    - python manage.py validate_templates
    - python manage.py check
    - python manage.py makemigrations --check --dry-run
