# Generated by Django 4.0.4 on 2022-04-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_group', models.CharField(max_length=50, unique=True)),
                ('creation_time', models.IntegerField(max_length=12)),
            ],
        ),
    ]
