# Generated by Django 4.0.4 on 2022-04-29 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_alter_group_creation_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='creation_time',
        ),
    ]
