# Generated by Django 4.0.4 on 2022-06-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_remove_group_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name_group',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
