# Generated by Django 4.0.4 on 2022-05-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_age_alter_student_first_name_and_more'),
        ('group', '0007_remove_group_students_group_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(related_name='students', to='students.student'),
        ),
    ]
