# Generated by Django 4.0.4 on 2022-07-29 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_alter_group_name_group'),
        ('group', '0008_alter_group_students'),
    ]

    operations = [
    ]
