# Generated by Django 4.0.4 on 2022-05-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_alter_exchange_buy_price_alter_exchange_sell_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='currency',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='source',
            field=models.CharField(default='privatbank', max_length=20),
        ),
    ]
