# Generated by Django 4.0.4 on 2022-05-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_alter_exchange_currency_alter_exchange_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='buy_price',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
