# Generated by Django 4.0.4 on 2022-06-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='seniority',
            field=models.IntegerField(null=True),
        ),
    ]
